### ISSUE TITLE
Pre existing parameters not appearing, but still exist in database

### ISSUE THREAD

**Issue by AndyL123** [DNNCommunity/DNN.IFrame#22]
## Describe the bug
iFrame instances with parameters no longer appear to have any parameters (on Parameters tab) although they still exist in database (IFrame_Parameters table).  

## To Reproduce
1. Go to an iFrame module which had parameters defined
2. Access 'Edit Options'
3. Check Parameters tab

## Expected behavior
Pre-existing parameters still to be there and operable.

## Error log
Attempting to re add a parameter fails (but could be because it already exists?) with:

Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Modules.IFrame.Components.ParametersInfo.get_PortalInfo() --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) at PetaPoco.Database.PrepareExecuteInsert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco, PocoData pd, List`1 names, List`1 values, IDbCommand cmd) at PetaPoco.Database.ExecuteInsert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco) at PetaPoco.Database.Insert(Object poco) at DotNetNuke.Data.RepositoryBase`1.Insert(T item) at DotNetNuke.Modules.IFrame.Components.ParametersController.AddParameter(ParametersInfo parameter) at DotNetNuke.Modules.IFrame.UI.IframeOptions.UpdateParameterButton_Click(Object sender, EventArgs e) --- End of inner exception stack trace ---

## Additional context
This is on DNN 9.4.1 with iFrame 8.1.2 - but I believe it started at DNN 9.4.0 with iFrame 8.1.1 (Ok at DNN 9.3.2, iFrame 8.1.1)

**Comment by AndyL123** [comment]
Clean install of DNN 9.4.1, clean install of iFrame 8.1.2, create page with an instance of the iFrame module, attempt to add a static value parameter, fails on attempt to commit.  Admin Log says:

InnerMessage:Exception has been thrown by the target of an invocation.
InnerStackTrace: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at PetaPoco.Database.PrepareExecuteInsert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco, PocoData pd, List`1 names, List`1 values, IDbCommand cmd)
   at PetaPoco.Database.ExecuteInsert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
   at PetaPoco.Database.Insert(Object poco)
   at DotNetNuke.Data.RepositoryBase`1.Insert(T item)
   at DotNetNuke.Modules.IFrame.Components.ParametersController.AddParameter(ParametersInfo parameter)
   at DotNetNuke.Modules.IFrame.UI.IframeOptions.UpdateParameterButton_Click(Object sender, EventArgs e)
